### ISSUE TITLE
Inconsistent image input size and image output size

### ISSUE THREAD

**Issue by Yorha4D** [mlinmg/ComfyUI-LaMA-Preprocessor#4] opened 2023-09-28 18:14 UTC
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/116185401/51f2ad7a-22d6-4b2a-8515-bff1acc4ad0d)
@mlinmg HI,I have discovered a new problem, as shown in the image. When I input an image size of 1024 * 1024, it uniformly expands by 256, but the output image is clearly not a square image.
But I found that as long as it doesn't increase the pixels up, down, left, and right at the same time, it will work well. As shown in the figure, I only added the upper and lower pixels, and it is not a problem.
To avoid issues, I have attempted to restart the computer, and my graphics card is RTX 4090, which should not have any memory related issues. I hope this is useful to you.
(This project is really cool, I have never felt so happy when using outpainting~)
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/116185401/747afdbb-ef78-4183-9f5c-f4001a8645cf)

**Comment by mlinmg** [comment] 2023-09-28 21:30
Pretty happy to hear that! Thanks for the report! As for the the multiple axis outpaint at the moment is currently under development, I plan to give the even the abilityto upload a non standard mask. at the moment it can only handle single axis outpaint (the code is already capable of doing multi axis outpaint but it has not been tested thoroughly so I'm waiting a bit to enable this feature) 
May I ask what workflow are you using? Those images are amazing!

**Comment by Yorha4D** [comment] 2023-09-29 05:44
> Pretty happy to hear that! Thanks for the report! As for the the multiple axis outpaint at the moment is currently under development, I plan to give the even the abilityto upload a non standard mask. at the moment it can only handle single axis outpaint (the code is already capable of doing multi axis outpaint but it has not been tested thoroughly so I'm waiting a bit to enable this feature)很高兴听到这个消息！感谢您的报告！至于目前正在开发的多轴外画，我计划甚至能够上传非标准蒙版。目前它只能处理单轴外画（代码已经能够进行多轴外画，但尚未经过彻底测试，所以我正在等待一段时间以启用此功能） May I ask what workflow are you using? Those images are amazing!请问您使用什么工作流程？这些图像令人惊叹！
@mlinmg  This sounds great! Regarding the image, I just added a few nodes to make it more automatic. The source image is here.
![ComfyUI_00025_](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/116185401/1b0ca230-d781-42fa-a153-103d776c1808)

**Comment by mlinmg** [comment] 2023-09-29 14:58
I close this since it is fixed with the last update

**Closed by mlinmg** 2023-09-29 14:58 UTC
Labels: enhancement

**Comment by xintron** [comment] 2023-12-12 12:56
I have a problem that seems similar to this issue (let me know if I should open a separate github issue).

I did outpaint on the top of an image and loaded this into comfy. I painted a mask to be inpainted and then ran it through the lamaPreprocessor. The output is unexpected and offset (centered?). I would expect the image/latent to be aligned to the bottom and not centered. Is this expected behavior?
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/40586/f2aa16dc-fa56-4b1c-8944-0bbe73dd552c)

**Comment by mlinmg** [comment] 2023-12-12 14:42
Yes there i am problem with the lama model implementation in which only symmetrical expansion is treated correctly, I’ve tried to solve this but without much success


Il giorno 12 dic 2023, alle ore 13:57, Marcus Carlsson ***@***.***> ha scritto:

﻿

I have a problem that seems similar to this issue (let me know if I should open a separate github issue).

I did outpaint on the top of an image and loaded this into comfy. I painted a mask to be inpainted and then ran it through the lamaPreprocessor. The output is unexpected and offset (centered?). I would expect the image/latent to be aligned to the bottom and not centered. Is this expected behavior?
image.png (view on web)<https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/40586/f2aa16dc-fa56-4b1c-8944-0bbe73dd552c>

**Comment by xintron** [comment] 2023-12-13 09:04
@mlinmg I did some testing and found that if you leave all 4 corners unmasked then the preprocessing works as expected. It doesn't take much to make this happen so at least there's a workaround. Not sure how this information can help or of there is anything that can be done as part of the node. Perhaps expanding the mask, setting it to unmasked, run preprocessor and then shrink mask/image again?

![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/40586/559e126c-0746-4e8c-8a51-efff4b361a1c)
